# Generated by Django 3.1.2 on 2020-11-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_atoffice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfiduser',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='rfiduser',
            name='kiosk_balance',
            field=models.IntegerField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfiduser',
            name='phone_mnumber',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfiduser',
            name='rfid',
            field=models.CharField(max_length=30),
        ),
    ]
