# Generated by Django 3.1.2 on 2020-11-04 06:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'products',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
