# Generated by Django 3.1.2 on 2020-11-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_kiosk_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='products',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.CharField(default='dsad2csagfdgf3', max_length=100),
            preserve_default=False,
        ),
    ]
